// Mocks generated by Mockito 5.4.4 from annotations
// in universal_notes_flutter/test/utils/update_helper_test.dart.
// Do not manually edit this file.

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:universal_notes_flutter/services/update_service.dart' as _i2;

// ignore_for_file: top_level_function_literal_block
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: unused_import

/// A class which mocks [UpdateService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateService extends _i1.Mock implements _i2.UpdateService {
  MockUpdateService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UpdateCheckResult> checkForUpdate() => (super.noSuchMethod(
        Invocation.method(
          #checkForUpdate,
          [],
        ),
        returnValue: _i4.Future<_i2.UpdateCheckResult>.value(
            _i2.UpdateCheckResult(_i2.UpdateCheckStatus.updateAvailable)),
        returnValueForMissingStub: _i4.Future<_i2.UpdateCheckResult>.value(
            _i2.UpdateCheckResult(_i2.UpdateCheckStatus.updateAvailable)),
      ) as _i4.Future<_i2.UpdateCheckResult>);
  @override
  String? getPlatformFileExtension() => (super.noSuchMethod(
        Invocation.method(
          #getPlatformFileExtension,
          [],
        ),
        returnValueForMissingStub: null,
      ) as String?);
}
