import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:http/http.dart' as http;
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:open_file/open_file.dart';
import 'package:path_provider/path_provider.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:plugin_platform_interface/plugin_platform_interface.dart';
import 'package:universal_notes_flutter/services/update_service.dart';
import 'package:universal_notes_flutter/utils/update_helper.dart';
import 'package:flutter/services.dart';

import 'update_helper_test.mocks.dart';

// Mocks for dependencies that will be generated by build_runner
@GenerateMocks([UpdateService, http.Client])

// Manual mock for the PermissionHandlerPlatform interface
class MockPermissionHandlerPlatform extends Mock
    with PluginPlatformInterfaceMixin
    implements PermissionHandlerPlatform {
  PermissionStatus mockStatus = PermissionStatus.granted;

  @override
  Future<PermissionStatus> requestPermissions(
      List<Permission> permissions) async {
    return mockStatus;
  }

  @override
  Future<PermissionStatus> checkPermissionStatus(Permission permission) async {
    return mockStatus;
  }
}

void main() {
  late MockUpdateService mockUpdateService;
  late MockClient mockHttpClient;
  late MockPermissionHandlerPlatform mockPermissionHandler;

  final updateInfo = UpdateInfo(
    version: '2.0.0',
    downloadUrl: 'http://example.com/update.apk',
  );

  // This setup is needed to mock platform-specific features
  setUpAll(() {
    TestWidgetsFlutterBinding.ensureInitialized();
    // Mock for path_provider
    const MethodChannel('plugins.flutter.io/path_provider')
        .setMockMethodCallHandler((MethodCall methodCall) async {
      if (methodCall.method == 'getTemporaryDirectory') {
        final tempDir = await Directory.systemTemp.createTemp('test_app');
        return tempDir.path;
      }
      return '.';
    });
  });

  setUp(() {
    mockUpdateService = MockUpdateService();
    mockHttpClient = MockClient();
    mockPermissionHandler = MockPermissionHandlerPlatform();
    PermissionHandlerPlatform.instance = mockPermissionHandler;
  });

  tearDownAll(() {
    const MethodChannel('plugins.flutter.io/path_provider')
        .setMockMethodCallHandler(null);
  });

  // Helper to build a testable widget tree
  Future<void> pumpTestWidget(
    WidgetTester tester,
    Function(BuildContext) action,
  ) async {
    await tester.pumpWidget(
      MaterialApp(
        home: Scaffold(
          body: Builder(
            builder: (context) => ElevatedButton(
              onPressed: () => action(context),
              child: const Text('Trigger Action'),
            ),
          ),
        ),
      ),
    );
  }

  group('UpdateHelper.checkForUpdate', () {
    testWidgets('shows checking, then no-update snackbar on manual check',
        (tester) async {
      when(mockUpdateService.checkForUpdate()).thenAnswer(
        (_) async => UpdateCheckResult(status: UpdateCheckStatus.noUpdate),
      );

      await pumpTestWidget(tester, (context) {
        UpdateHelper.checkForUpdate(
          context,
          isManual: true,
          updateService: mockUpdateService,
        );
      });

      await tester.tap(find.byType(ElevatedButton));
      await tester.pump(); // Show "Verificando..."
      expect(find.text('Verificando atualizações...'), findsOneWidget);

      await tester.pumpAndSettle(); // Complete the check
      expect(find.text('Você já tem a versão mais recente.'), findsOneWidget);
    });

    testWidgets('shows error snackbar on manual check when an error occurs',
        (tester) async {
      when(mockUpdateService.checkForUpdate()).thenAnswer(
        (_) async => UpdateCheckResult(
            status: UpdateCheckStatus.error, errorMessage: 'Network Error'),
      );

      await pumpTestWidget(tester, (context) {
        UpdateHelper.checkForUpdate(
          context,
          isManual: true,
          updateService: mockUpdateService,
        );
      });

      await tester.tap(find.byType(ElevatedButton));
      await tester.pumpAndSettle();
      expect(find.text('Network Error'), findsOneWidget);
    });

    testWidgets('shows update dialog when an update is available',
        (tester) async {
      when(mockUpdateService.checkForUpdate()).thenAnswer(
        (_) async => UpdateCheckResult(
            status: UpdateCheckStatus.updateAvailable, updateInfo: updateInfo),
      );

      await pumpTestWidget(tester, (context) {
        UpdateHelper.checkForUpdate(
          context,
          isManual: true,
          updateService: mockUpdateService,
        );
      });

      await tester.tap(find.byType(ElevatedButton));
      await tester.pumpAndSettle();

      expect(find.byType(AlertDialog), findsOneWidget);
      expect(find.text('Atualização Disponível'), findsOneWidget);
      expect(find.textContaining('2.0.0'), findsOneWidget);
    });

    testWidgets(
        'starts download when "Sim, atualizar" is tapped and permission is granted',
        (tester) async {
      // Arrange
      when(mockUpdateService.checkForUpdate()).thenAnswer(
        (_) async => UpdateCheckResult(
            status: UpdateCheckStatus.updateAvailable, updateInfo: updateInfo),
      );
      when(mockHttpClient.get(Uri.parse(updateInfo.downloadUrl)))
          .thenAnswer((_) async => http.Response('fake apk data', 200));

      // We are not mocking OpenFile, so we just check the flow before it

      // Act
      await pumpTestWidget(tester, (context) {
        UpdateHelper.checkForUpdate(
          context,
          isManual: true,
          updateService: mockUpdateService,
          isAndroidOverride: true,
          httpClient: mockHttpClient,
        );
      });

      await tester.tap(find.byType(ElevatedButton));
      await tester.pumpAndSettle(); // Show dialog

      await tester.tap(find.text('Sim, atualizar'));
      await tester.pump(); // Close dialog, show download snackbar

      // Assert
      expect(find.text('Baixando atualização... Por favor, aguarde.'),
          findsOneWidget);

      await tester.pumpAndSettle(); // Finish download

      verify(mockHttpClient.get(Uri.parse(updateInfo.downloadUrl))).called(1);
    });

    testWidgets('shows permission error if permission is denied',
        (tester) async {
      // Arrange
      mockPermissionHandler.mockStatus = PermissionStatus.denied;
      when(mockUpdateService.checkForUpdate()).thenAnswer(
        (_) async => UpdateCheckResult(
            status: UpdateCheckStatus.updateAvailable, updateInfo: updateInfo),
      );

      // Act
      await pumpTestWidget(tester, (context) {
        UpdateHelper.checkForUpdate(
          context,
          isManual: true,
          updateService: mockUpdateService,
          isAndroidOverride: true,
          httpClient: mockHttpClient,
        );
      });

      await tester.tap(find.byType(ElevatedButton));
      await tester.pumpAndSettle(); // Show dialog

      await tester.tap(find.text('Sim, atualizar'));
      await tester.pumpAndSettle(); // Request permission and show snackbar

      // Assert
      expect(
          find.text(
              'Permissão para instalar pacotes é necessária para a atualização.'),
          findsOneWidget);
    });
  });
}
