// This is a stub file for CI/CD analysis.
// The real firebase_options.dart is generated by FlutterFire CLI
// and is gitignored to protect API keys.
//
// For local development, run: flutterfire configure
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Stub [FirebaseOptions] for CI/CD environments.
///
/// This file allows `dart analyze` to pass in CI where the real
/// `firebase_options.dart` is not available.
class DefaultFirebaseOptions {
  /// Returns stub options based on the current platform.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'stub-api-key',
    appId: 'stub-app-id',
    messagingSenderId: 'stub-sender-id',
    projectId: 'stub-project-id',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'stub-api-key',
    appId: 'stub-app-id',
    messagingSenderId: 'stub-sender-id',
    projectId: 'stub-project-id',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'stub-api-key',
    appId: 'stub-app-id',
    messagingSenderId: 'stub-sender-id',
    projectId: 'stub-project-id',
    iosBundleId: 'stub-bundle-id',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'stub-api-key',
    appId: 'stub-app-id',
    messagingSenderId: 'stub-sender-id',
    projectId: 'stub-project-id',
    iosBundleId: 'stub-bundle-id',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'stub-api-key',
    appId: 'stub-app-id',
    messagingSenderId: 'stub-sender-id',
    projectId: 'stub-project-id',
  );
}
