import 'dart:io';
import 'dart:convert';

void main(List<String> args) {
  print('--- Hermes PR Summary Generator ---');

  final coverageFile = File(
    'Notes-Hub/coverage.json',
  ); // Updated via lcov-parse in CI
  final healthFile = File('health_output.txt');
  final changelogFile = File('changelog.md');
  final toolchainFile = File('toolchain.lock.json');
  final scoreFile = File('impact_score.json');
  final pulseFile = File('project_pulse.json');

  final sb = StringBuffer();
  sb.writeln('## 📦 Hermes Pipeline Summary');

  // New: Impact Score
  if (scoreFile.existsSync()) {
    try {
      final scoreData = json.decode(scoreFile.readAsStringSync());
      final grade = scoreData['grade'];
      final reason = scoreData['reason'];
      sb.writeln('\n### 🏆 PR Impact Grade: `$grade`');
      sb.writeln('> $reason\n');
    } catch (_) {}
  }

  // New: Pulse Trends
  if (pulseFile.existsSync()) {
    try {
      final history = json.decode(pulseFile.readAsStringSync()) as List;
      if (history.length >= 2) {
        final current = history.last['metrics'];
        final previous = history[history.length - 2]['metrics'];

        sb.writeln('### 📈 Project Pulse (Trend Analysis)');
        final covDiff =
            (current['coverage'] as double) - (previous['coverage'] as double);
        final sizeDiffKB = ((current['apk_size_bytes'] as int) -
                (previous['apk_size_bytes'] as int)) /
            1024;

        final covEmoji = covDiff >= 0 ? '🟢 🔼' : '🔴 🔽';
        final sizeEmoji = sizeDiffKB <= 0 ? '🟢 🔽' : '🟡 🔼';

        sb.writeln(
            '- **Coverage:** `${current['coverage']}%` ($covEmoji ${covDiff.toStringAsFixed(1)}%)');
        sb.writeln(
            '- **Binary Size:** `${(current['apk_size_bytes'] / (1024 * 1024)).toStringAsFixed(1)} MB` ($sizeEmoji ${sizeDiffKB.toStringAsFixed(1)} KB)');
        sb.writeln('');
      }
    } catch (_) {}
  }
  sb.writeln(
    '\n> [!TIP]\n> This is an automated summary of the latest CI run. Keep shipping! 🚀\n',
  );

  // 0. Toolchain
  if (toolchainFile.existsSync()) {
    try {
      final data = json.decode(toolchainFile.readAsStringSync());
      sb.writeln('### 🔒 Toolchain Environment');
      sb.writeln('- **Flutter:** `${data['flutter']}`');
      sb.writeln('- **Dart:** `${data['dart']}`');
    } catch (_) {}
  }

  // 1. Coverage
  if (coverageFile.existsSync()) {
    try {
      final data = json.decode(coverageFile.readAsStringSync());
      final percentage = data['percentage'] ?? '0.00';
      final icon = double.parse(percentage) >= 80 ? '✅' : '❌';
      sb.writeln('### $icon Code Coverage');
      sb.writeln('- **Total:** `${percentage}%`');
    } catch (e) {
      sb.writeln('### ⚠️ Code Coverage');
      sb.writeln('- Error parsing coverage data.');
    }
  } else {
    sb.writeln('### ⚪ Code Coverage');
    sb.writeln('- Statistics not available.');
  }

  // 2. Health Audit
  if (healthFile.existsSync()) {
    final healthContent = healthFile.readAsStringSync();
    final hasErrors = healthContent.contains('❌ ERROR');
    final icon = hasErrors ? '❌' : '✅';
    sb.writeln('\n### $icon Health Audit');
    if (hasErrors) {
      sb.writeln(
        '<details><summary>Click to view errors</summary>\n\n```\n$healthContent\n```\n</details>',
      );
    } else {
      sb.writeln('- All health checks passed (Artifact sizes, Secret leaks).');
    }
  }

  // 3. Size Drift
  final driftFile = File('size_drift.md');
  if (driftFile.existsSync()) {
    sb.writeln('\n' + driftFile.readAsStringSync());
  }

  // 4. License Audit
  final licenseFile = File('license_audit.txt');
  if (licenseFile.existsSync()) {
    final licenseContent = licenseFile.readAsStringSync();
    final hasErrors = licenseContent.contains('❌');
    final icon = hasErrors ? '❌' : '📜';
    sb.writeln('\n### $icon License Audit');
    if (hasErrors) {
      sb.writeln(
        '<details><summary>Click to view license issues</summary>\n\n```\n$licenseContent\n```\n</details>',
      );
    } else {
      sb.writeln('- All dependency licenses are compliant.');
    }
  }

  // 5. Dependency Updates
  final updatesFile = File('dependency_updates.md');
  if (updatesFile.existsSync()) {
    sb.writeln('\n' + updatesFile.readAsStringSync());
  }

  // 6. Changelog
  if (changelogFile.existsSync()) {
    final changelog = changelogFile.readAsStringSync();
    sb.writeln('\n### 📝 Proposed Changelog');
    sb.writeln(
      '<details><summary>Expand Changelog</summary>\n\n$changelog\n</details>',
    );
  }

  sb.writeln('\n---');
  sb.writeln('*Generated by Hermes DevOps Specialist*');

  File('pr_summary.md').writeAsStringSync(sb.toString());
  print('✅ PR Summary generated successfully.');
}
