import 'dart:io';
import 'dart:convert';

void main(List<String> args) {
  print('--- Hermes PR Summary Generator ---');

  final coverageFile = File(
    'Notes-Hub/coverage.json',
  ); // Updated via lcov-parse in CI
  final healthFile = File('health_output.txt');
  final changelogFile = File('changelog.md');

  final sb = StringBuffer();
  sb.writeln('## 📦 Hermes Pipeline Summary');
  sb.writeln(
    '\n> [!TIP]\n> This is an automated summary of the latest CI run. Keep shipping! 🚀\n',
  );

  // 1. Coverage
  if (coverageFile.existsSync()) {
    try {
      final data = json.decode(coverageFile.readAsStringSync());
      final percentage = data['percentage'] ?? '0.00';
      final icon = double.parse(percentage) >= 80 ? '✅' : '❌';
      sb.writeln('### $icon Code Coverage');
      sb.writeln('- **Total:** `${percentage}%`');
    } catch (e) {
      sb.writeln('### ⚠️ Code Coverage');
      sb.writeln('- Error parsing coverage data.');
    }
  } else {
    sb.writeln('### ⚪ Code Coverage');
    sb.writeln('- Statistics not available.');
  }

  // 2. Health Audit
  if (healthFile.existsSync()) {
    final healthContent = healthFile.readAsStringSync();
    final hasErrors = healthContent.contains('❌ ERROR');
    final icon = hasErrors ? '❌' : '✅';
    sb.writeln('\n### $icon Health Audit');
    if (hasErrors) {
      sb.writeln(
        '<details><summary>Click to view errors</summary>\n\n```\n$healthContent\n```\n</details>',
      );
    } else {
      sb.writeln('- All health checks passed (Artifact sizes, Secret leaks).');
    }
  }

  // 3. Size Drift
  final driftFile = File('size_drift.md');
  if (driftFile.existsSync()) {
    sb.writeln('\n' + driftFile.readAsStringSync());
  }

  // 4. License Audit
  final licenseFile = File('license_audit.txt');
  if (licenseFile.existsSync()) {
    final licenseContent = licenseFile.readAsStringSync();
    final hasErrors = licenseContent.contains('❌');
    final icon = hasErrors ? '❌' : '📜';
    sb.writeln('\n### $icon License Audit');
    if (hasErrors) {
      sb.writeln(
        '<details><summary>Click to view license issues</summary>\n\n```\n$licenseContent\n```\n</details>',
      );
    } else {
      sb.writeln('- All dependency licenses are compliant.');
    }
  }

  // 5. Changelog
  if (changelogFile.existsSync()) {
    final changelog = changelogFile.readAsStringSync();
    sb.writeln('\n### 📝 Proposed Changelog');
    sb.writeln(
      '<details><summary>Expand Changelog</summary>\n\n$changelog\n</details>',
    );
  }

  sb.writeln('\n---');
  sb.writeln('*Generated by Hermes DevOps Specialist*');

  File('pr_summary.md').writeAsStringSync(sb.toString());
  print('✅ PR Summary generated successfully.');
}
