// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3x5Bx4Bxt5X9ON9WonBqrUeUyJ9OQTcg',
    appId: '1:542251776386:web:62f1b1373d48c96baef79b',
    messagingSenderId: '542251776386',
    projectId: 'noootes-app',
    authDomain: 'noootes-app.firebaseapp.com',
    storageBucket: 'noootes-app.firebasestorage.app',
    measurementId: 'G-30VLCP5DXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIKMM7gT7fDteG66PbsxavPA5tHy4DGrQ',
    appId: '1:542251776386:android:81e42b4a90a944e2aef79b',
    messagingSenderId: '542251776386',
    projectId: 'noootes-app',
    storageBucket: 'noootes-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ-BVY_VGMJGic4Z171IE3kfHT7aJYdEc',
    appId: '1:542251776386:ios:c1d515b26722a8e2aef79b',
    messagingSenderId: '542251776386',
    projectId: 'noootes-app',
    storageBucket: 'noootes-app.firebasestorage.app',
    iosBundleId: 'com.notes.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ-BVY_VGMJGic4Z171IE3kfHT7aJYdEc',
    appId: '1:542251776386:ios:c1d515b26722a8e2aef79b',
    messagingSenderId: '542251776386',
    projectId: 'noootes-app',
    storageBucket: 'noootes-app.firebasestorage.app',
    iosBundleId: 'com.notes.app',
  );
}
