<<<<<<< HEAD
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3x5Bx4Bxt5X9ON9WonBqrUeUyJ9OQTcg',
    appId: '1:542251776386:web:62f1b1373d48c96baef79b',
    messagingSenderId: '542251776386',
    projectId: 'noootes-app',
    authDomain: 'noootes-app.firebaseapp.com',
    storageBucket: 'noootes-app.firebasestorage.app',
    measurementId: 'G-30VLCP5DXN',
  );
=======
// Copyright 2023, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// This file is generated automatically by the FlutterFire CLI.
// Please do not modify this file manually.

/// A placeholder class for Firebase options.
///
/// This class is used to avoid build errors when the real `firebase_options.dart`
/// file is not present. This is common in environments where the Firebase
/// project is not configured.
class DefaultFirebaseOptions {
  static get currentPlatform {
    throw UnimplementedError(
      'DefaultFirebaseOptions have not been configured for this platform.',
    );
  }
>>>>>>> 3ecb4e55dca0464a4bcca61a30500d1f259c0cb7
}
