// This is a stub file for CI/CD analysis.
// The real firebase_options.dart is generated by FlutterFire CLI
// and is gitignored to protect API keys.
//
// For local development, run: flutterfire configure
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Stub [FirebaseOptions] for CI/CD environments.
///
/// This file allows `dart analyze` to pass in CI where the real
/// `firebase_options.dart` is not available.
class DefaultFirebaseOptions {
  /// Returns stub options based on the current platform.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3x5Bx4Bxt5X9ON9WonBqrUeUyJ9OQTcg',
    appId: '1:542251776386:web:62f1b1373d48c96baef79b',
    messagingSenderId: '542251776386',
    projectId: 'noootes-app',
    authDomain: 'noootes-app.firebaseapp.com',
    storageBucket: 'noootes-app.firebasestorage.app',
    measurementId: 'G-30VLCP5DXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIKMM7gT7fDteG66PbsxavPA5tHy4DGrQ',
    appId: '1:542251776386:android:81e42b4a90a944e2aef79b',
    messagingSenderId: '542251776386',
    projectId: 'noootes-app',
    storageBucket: 'noootes-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ-BVY_VGMJGic4Z171IE3kfHT7aJYdEc',
    appId: '1:542251776386:ios:4d1d9f23b64a0a01aef79b',
    messagingSenderId: '542251776386',
    projectId: 'noootes-app',
    storageBucket: 'noootes-app.firebasestorage.app',
    androidClientId: '542251776386-a0el0b32ppoor4l305ej830ad926appt.apps.googleusercontent.com',
    iosClientId: '542251776386-flt1kc52alrit79v0k8j38nkl0pbancc.apps.googleusercontent.com',
    iosBundleId: 'noootes-app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ-BVY_VGMJGic4Z171IE3kfHT7aJYdEc',
    appId: '1:542251776386:ios:4d1d9f23b64a0a01aef79b',
    messagingSenderId: '542251776386',
    projectId: 'noootes-app',
    storageBucket: 'noootes-app.firebasestorage.app',
    androidClientId: '542251776386-a0el0b32ppoor4l305ej830ad926appt.apps.googleusercontent.com',
    iosClientId: '542251776386-flt1kc52alrit79v0k8j38nkl0pbancc.apps.googleusercontent.com',
    iosBundleId: 'noootes-app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3x5Bx4Bxt5X9ON9WonBqrUeUyJ9OQTcg',
    appId: '1:542251776386:web:62f1b1373d48c96baef79b',
    messagingSenderId: '542251776386',
    projectId: 'noootes-app',
    authDomain: 'noootes-app.firebaseapp.com',
    storageBucket: 'noootes-app.firebasestorage.app',
    measurementId: 'G-30VLCP5DXN',
  );

}